src/Entity/Liste.php
<?php

namespace App\Entity;

use App\Repository\ListeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ListeRepository::class)]
#[Vich\Uploadable]
class Liste
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 50)]
    private ?string $theme = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $password = null;

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'liste', fileNameProperty: 'imageName', size: 'imageSize')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(nullable: true)]
    private ?int $imageSize = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_ouveture = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin_ouverture = null;

    #[ORM\OneToMany(mappedBy: 'liste', targetEntity: Gift::class)]
    private Collection $giftId;

    #[ORM\ManyToOne(inversedBy: 'listeId')]
    private ?User $userId = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isArchived = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isPrivate = null;

    public function __construct()
    {
        $this->giftId = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function getDateOuveture(): ?\DateTimeInterface
    {
        return $this->date_ouveture;
    }

    public function setDateOuveture(\DateTimeInterface $date_ouveture): self
    {
        $this->date_ouveture = $date_ouveture;

        return $this;
    }

    public function getDateFinOuverture(): ?\DateTimeInterface
    {
        return $this->date_fin_ouverture;
    }

    public function setDateFinOuverture(?\DateTimeInterface $date_fin_ouverture): self
    {
        $this->date_fin_ouverture = $date_fin_ouverture;

        return $this;
    }

    /**
     * @return Collection<int, Gift>
     */
    public function getGiftId(): Collection
    {
        return $this->giftId;
    }

    public function addGiftId(Gift $giftId): static
    {
        if (!$this->giftId->contains($giftId)) {
            $this->giftId->add($giftId);
            $giftId->setListe($this);
        }

        return $this;
    }

    public function removeGiftId(Gift $giftId): static
    {
        if ($this->giftId->removeElement($giftId)) {
            // set the owning side to null (unless already changed)
            if ($giftId->getListe() === $this) {
                $giftId->setListe(null);
            }
        }

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->userId;
    }

    public function setUserId(?User $userId): static
    {
        $this->userId = $userId;

        return $this;
    }

    public function isIsArchived(): ?bool
    {
        return $this->isArchived;
    }

    public function setIsArchived(?bool $isArchived): static
    {
        $this->isArchived = $isArchived;

        return $this;
    }

    public function isIsPrivate(): ?bool
    {
        return $this->isPrivate;
    }

    public function setIsPrivate(?bool $isPrivate): static
    {
        $this->isPrivate = $isPrivate;

        return $this;
    }
}

src/Form/ListeType.php
<?php

namespace App\Form;

use App\Entity\Liste;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ListeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class,[
                'attr'=>[
                    'class'=>''
                ],
                'label'=>'Titre'
            ])
            ->add('description', TextType::class,[
                'attr'=>[
                    'class'=>''
                ],
                'label'=>'Description'
            ])
            ->add('imageFile', VichImageType::class,[
                'attr'=>[
                    'class'=>''
                ],
                'label'=>'Couverture de la liste',
                'download_label'=>true,
            ])
            ->add('theme',TextType::class,[
                'attr'=>[
                    'class'=>''
                ],
                'label'=>'Thème'
            ])
            ->add('isPrivate', CheckboxType::class,[
                'attr'=>[
                    'class'=>''
                ],
                'label'=>'Cochez si vous voulez que votre liste soit privée',
                'required'=>'false'
            ])
            ->add('password', PasswordType::class,[
                'attr'=>[
                    'class'=>''
                ],
                'label'=>'Mot de passe',
                'required'=>'false'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Liste::class,
        ]);
    }
}

src/Controller/ListeController.php
<?php

namespace App\Controller;

use App\Entity\Liste;
use App\Entity\User;
use App\Form\ListeType;
use App\Repository\ListeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\DependencyInjection\Compiler\ResolveBindingsPass;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/liste')]
class ListeController extends AbstractController
{
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/', name: 'app_liste_index', methods: ['GET'])]
    public function index(ListeRepository $listeRepository): Response
    {
        return $this->render('liste/index.html.twig', [
            'listes' => $listeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_liste_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ListeRepository $listeRepository): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        if (!$user->isIsActive()) {
            return $this->render('resend_verif');
        } else {
            $liste = new Liste();
            $form = $this->createForm(ListeType::class, $liste);
            $form->handleRequest($request);

            $dateOuverture = $liste->setDateOuveture(new \DateTime());
            $liste->setUserId($this->getUser());
            $liste->setIsArchived(false);

            if ($form->isSubmitted() && $form->isValid()) {
                $listeRepository->save($liste, true);

                return $this->redirectToRoute('app_my_list', [], Response::HTTP_SEE_OTHER);
            }

            return $this->renderForm('liste/new.html.twig', [
                'liste' => $liste,
                'form' => $form,
            ]);
        }
    }

    #[Route('/mes-listes', name: 'app_my_list', methods: ['GET'])]
    public function myList(Request $request): Response
    {
        $user = $this->getUser();
        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        $listes = $user->getListeId()->filter(function ($liste) {
            return !$liste->isIsArchived();
        });

        return $this->render('liste/mylist.html.twig', [
            'listes' => $listes,
        ]);
    }


    #[Route('/{id}', name: 'app_liste_show', methods: ['GET'])]
    public function show(Liste $liste, Request $request): Response
    {
        // Vérifier si la liste est privée et si un mot de passe a été fourni et est correct
        if ($liste->isIsPrivate() && !$this->isAuthorized($request, $liste)) {
            return $this->redirectToRoute('app_mdp_list', ['id' => $liste->getId()]);
        }

        $gift = $liste->getGiftId();
        return $this->render('liste/show.html.twig', [
            'liste' => $liste,
            'gift' => $gift
        ]);
    }

    // Méthode pour vérifier si le mot de passe a été fourni et est correct
    private function isAuthorized(Request $request, Liste $liste): bool
    {
        $motDePasseFourni = $request->getSession()->get('liste_' . $liste->getId() . '_mdp');
        return $motDePasseFourni === $liste->getPassword();
    }

    #[Route('/get-mdp/{id}', name: 'app_mdp_list', methods: ['GET', 'POST'])]
    public function getMdp(Liste $liste, Request $request): Response
    {
        if ($request->isMethod('POST')) {
            $motDePasseFourni = $request->request->get('mot_de_passe');

            if ($motDePasseFourni === $liste->getPassword()) {
                // Stocker le mot de passe dans la session pour les futures vérifications
                $request->getSession()->set('liste_' . $liste->getId() . '_mdp', $motDePasseFourni);
                return $this->redirectToRoute('app_liste_show', ['id' => $liste->getId()]);
            } else {
                $this->addFlash('error', 'Mot de passe incorrect');
            }
        }

        return $this->render('liste/getMdpListe.html.twig', [
            'liste' => $liste,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_liste_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Liste $liste, ListeRepository $listeRepository): Response
    {
        $form = $this->createForm(ListeType::class, $liste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $listeRepository->save($liste, true);

            return $this->redirectToRoute('app_liste_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('liste/edit.html.twig', [
            'liste' => $liste,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_liste_delete', methods: ['POST'])]
    public function delete(Request $request, Liste $liste, ListeRepository $listeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $liste->getId(), $request->request->get('_token'))) {
            $listeRepository->remove($liste, true);
        }

        return $this->redirectToRoute('app_liste_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/ajout-cadeau', name: 'app_add_gift', methods: ["POST"])]
    public function showGifts($listeId): Response
    {
        $liste = $this->getDoctrine()->getRepository(Liste::class)->find($listeId);

        if (!$liste) {
            return $this->redirectToRoute('page_erreur');
        }

        $gifts = $liste->getGifts();

        return $this->render('liste/show_gifts.html.twig', [
            'liste' => $liste,
            'gifts' => $gifts,
        ]);
    }

    #[Route('/{id/share', name: 'list_share', methods: ['GET'])]
    public function listShare(Request $request, $id): Response
    {
        $sentitymanager = $this->getDoctrine()->getManager();
        $liste = $sentitymanager->getRepository(Liste:: class)->find($id);

        if (!$liste) {
            throw $this->createNotFoundException('Liste non trouvée pour l\'ID ' . $id);
        }

        // Générez un lien de partage en fonction de l'ID de la liste
        $shareLink = $this->generateUrl('app_liste_show', [
            'id' => $liste->getId(),
        ], true);

        return $this->render('liste/share.html.twig', [
            'liste' => $liste,
            'shareLink' => $shareLink,
        ]);
    }


    #[Route('/archive-liste/{id}', name: 'archive_liste', methods: ['POST', 'GET'])]
    public function archiveListe(Request $request, $id, EntityManagerInterface $entityManager, ListeRepository $listeRepository): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        // Utilisation du repository injecté
        $liste = $listeRepository->find($id);

        if (!$liste) {
            throw $this->createNotFoundException('Liste introuvable');
        }

        $liste->setIsArchived(true);
        $entityManager->flush();

        //return $this->redirectToRoute('my_archived_list');
        return $this->redirectToRoute('all_my_archived_list');
    }

    #[Route('/unarchive-liste/{id}', name: 'unarchive_liste', methods: ['POST'])]
    public function unarchiveListe(Request $request, $id, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        //$entityManager = $this->getDoctrine()->getManager();
        $liste = $entityManager->getRepository(ListeCadeau::class)->find($id);

        if (!$liste) {
            throw $this->createNotFoundException('Liste introuvable');
        }

        $liste->setIsArchived(false);
        $entityManager->flush();

        return $this->redirectToRoute('liste/mylist.html.twig');
    }

    #[Route('/ma-liste-archivee/{id}', name: 'my_archived_list', methods: ['GET'])]
    public function myArchivedList(Liste $liste, Request $request): Response
    {
        $user = $this->getUser();
        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        if ($liste->isIsPrivate() && !$this->isAuthorized($request, $liste)) {
            return $this->redirectToRoute('app_mdp_list', ['id' => $liste->getId()]);
        }

        $gift = $liste->getGiftId();

        return $this->render('liste/show.html.twig', [
            'liste' => $liste,
            'gift' => $gift
        ]);
    }

    #[Route('/mes-listes-archivees', name: 'all_my_archived_list', methods: ['GET'])]
    public function allMyArchivedList(ListeRepository $listeRepository): Response
    {
        $user = $this->getUser();
        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        $listes = $user->getListeId()->filter(function ($liste) {
            return $liste->isIsArchived();
        });

        return $this->render('liste/allMyArchivedList.html.twig', [
            'listes' => $listes,
        ]);
    }

}

templates/liste/_delete_form.html.twig
<form method="post" action="{{ path('app_liste_delete', {'id': liste.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ liste.id) }}">
    <button class="btn">Delete</button>
</form>

templates/liste/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/liste/allMyArchivedList.html.twig
{% extends 'base.html.twig' %}
{% block title %} Mes listes archivées {% endblock %}
{% block body %}
<h1 class="text-center">Mes listes arcivhées</h1>
{% endblock %}

templates/liste/edit.html.twig
{% extends './base.html.twig' %}

{% block title %}Edit Liste{% endblock %}

{% block body %}
    <h1>Edit Liste</h1>

    {{ include('liste/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_liste_index') }}">back to list</a>

    {{ include('liste/_delete_form.html.twig') }}
{% endblock %}

templates/liste/getMdpListe.html.twig
{% extends 'base.html.twig' %}
{% block title %} Mot de passe {% endblock %}
{% block body %}
    <h1 class="text-center">La liste est privée, entrez-y le mot de passe afin d'y accéder</h1>
    <form action="{{ path('app_mdp_list', {'id': liste.id}) }}" method="post">
        <input type="password" placeholder="Mot de passe" name="mot_de_passe">
        <button type="submit">Accéder à la liste</button>
    </form>
    {% if app.flashes('error') %}
        <div class="alert alert-danger">
            {{ app.flashes('error')[0] }}
        </div>
    {% endif %}
{% endblock %}

templates/liste/index.html.twig
{% extends './base.html.twig' %}

{% block title %}Liste index{% endblock %}

{% block body %}
    <h1>Liste index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Cover</th>
                <th>Theme</th>
                <th>Status</th>
                <th>Password</th>
                <th>Date_ouveture</th>
                <th>Date_fin_ouverture</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for liste in listes %}
            <tr>
                <td>{{ liste.id }}</td>
                <td>{{ liste.title }}</td>
                <td>{{ liste.description }}</td>
                <td>{{ liste.imageFile }}</td>
                <td>{{ liste.theme }}</td>
                <td>{{ liste.status }}</td>
                <td>{{ liste.password }}</td>
                <td>{{ liste.dateOuveture ? liste.dateOuveture|date('Y-m-d') : '' }}</td>
                <td>{{ liste.dateFinOuverture ? liste.dateFinOuverture|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_liste_show', {'id': liste.id}) }}">show</a>
                    <a href="{{ path('app_liste_edit', {'id': liste.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_liste_new') }}">Create new</a>
{% endblock %}

templates/liste/myArchivedList.html.twig
{% extends 'base.html.twig' %}

{% block title %} Mes listes archivées {% endblock %}
            {% for liste in listes %}
                <li>
                    <a>{{ liste.title }}</a>
                </li>
            {% endfor %}
{% endblock %}

templates/liste/mylist.html.twig
{% extends './base.html.twig' %}
{% block title %} Mes listes de cadeaux {% endblock %}

{% block body %}
    {% if listes is empty %}
        <p>Vous n'avez pas encore créé de listes de cadeaux.</p>
        <p><a href="{{ path('app_liste_new') }}">Ajouter votre liste ici</a></p>
    {% else %}
        <ul>
            {% for liste in listes %}
                <li>
                    <a href="{{ path('app_liste_show', {'id': liste.id}) }}">{{ liste.title }}</a>
                </li>
            {% endfor %}
        </ul>
        <p><a href="{{ path('app_liste_new') }}">Ajouter une nouvelle liste</a></p>
    {% endif %}
{% endblock %}

templates/liste/new.html.twig
{% extends './base.html.twig' %}

{% block title %}New Liste{% endblock %}

{% block body %}
    <h1>Create new Liste</h1>

    {{ include('liste/_form.html.twig') }}

    <a href="{{ path('app_liste_index') }}">back to list</a>
{% endblock %}

templates/liste/show.html.twig
{% extends './base.html.twig' %}

{% block title %}Liste{% endblock %}

{% block body %}
    <header class="h-50">
        <div class="p-5 text-center bg-image"
             style="background-image: url('{{ vich_uploader_asset(liste, 'imageFile') }}'); ">
            <div class="text-center bg-body-tertiary">
                <div>
                    <h1 class="mb-3">{{ liste.title }}</h1>
                    <h2 class="mb-3">{{ liste.description }}</h2>
                </div>
            </div>
        </div>
    </header>

    <div class="d-flex">
        <h2>Lien de partage :</h2>
        <p><a href="{{ path('list_share', {'id': liste.id}) }}">Partager cette liste</a></p>
    </div>

    <div class="d-flex">
        <p>Cette liste a été créée le {{ liste.dateOuveture ? liste.dateOuveture|date('Y-m-d') : '' }} dans le thème
            de {{ liste.theme }}</p>
    </div>

    {% if gift is empty %}
        <p>Votre liste est actuellement vide. <a href="{{ path('create_gift', {'listeId': liste.id}) }}">Ajouter vos cadeaux ici</a></p>
    {% else %}
        {% for gift in liste.getGiftId() %}
                <a href="{{ path('app_gift_show', {'id': gift.id}) }}">{{ gift.Name }}</a>
                {{ gift.Price }}
                {% if gift.imageFile is defined %}
                    <img src="{{ vich_uploader_asset(gift, 'imageFile') }}" alt="{{ gift.imageName }}">
                {% else %}
                    <img src="{{ gift.imageName }}" alt="{{ gift.imageName }}">
                {% endif %}
                {#                <td><a href="{{ path('app_gift_show', {'id': gift.id}) }}">Lien du cadeau</a></td> #}
        {% endfor %}
    {% endif %}

    {% if app.user is same as liste.userId %}

        <a href="{{ path('app_liste_index') }}">back to list</a>

        <a href="{{ path('app_liste_edit', {'id': liste.id}) }}">edit</a>

        {{ include('liste/_delete_form.html.twig') }}
        <a href="{{ path('create_gift', {'listeId': liste.id}) }}">Ajouter un nouveau cadeau</a>

        <a href="{{ path('archive_liste', {'id': liste.id}) }}" type="button"> Archiver la liste</a>

    {% endif %}
    {#    <a href="{{ path('app_gift_new') }}">Ajouter un nouveau cadeau</a> #}

    <p>{{ liste.dateFinOuverture ? 'liste close le ' + liste.dateFinOuverture|date('Y-m-d') : '' }}</p>
{% endblock %}